import { Category, Product, ProductVariant, ProductInquiry, CustomFurnitureRequest, GalleryItem } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-home-furniture', name: 'Home Furniture', slug: 'home-furniture', description: 'Premium wooden sofas, wardrobes, luxury cots, dining tables, and side boards.', image_url: '/carousel-1.jpg' },
  { id: 'cat-office-furniture', name: 'Office Furniture', slug: 'office-furniture', description: 'Executive desks, managerial cabins, storage credentials, and custom panels.', image_url: '/images/office-furniture.jpg' },
  { id: 'cat-study-tables', name: 'Study Tables', slug: 'study-tables', description: 'Modern student study tables, computer desks, and library workspaces.', image_url: '/images/office-furniture.jpg' },
  { id: 'cat-sofas', name: 'Sofas', slug: 'sofas', description: 'Solid teakwood sofas, cushioned sectional lounges, and sliding sofa-beds.', image_url: '/carousel-1.jpg' },
  { id: 'cat-beds', name: 'Beds', slug: 'beds', description: 'Handcrafted apple-motif king-size cots, royal teak wood double beds, and smart beds.', image_url: '/images/custom-furniture.jpg' },
  { id: 'cat-dining-tables', name: 'Dining Tables', slug: 'dining-tables', description: 'Teakwood and tempered glass 6-seater and 8-seater dining table sets.', image_url: '/images/dining-tables.jpg' },
  { id: 'cat-office-chairs', name: 'Office Chairs', slug: 'office-chairs', description: 'Ergonomic high-back executive mesh and leather cabin swivel chairs.', image_url: '/carousel-1.jpg' },
  { id: 'cat-plastic-chairs', name: 'Plastic Chairs', slug: 'plastic-chairs', description: 'Rugged, high-quality molded plastic chairs for commercial & residential uses.', image_url: '/images/plastic-chairs.jpg' },
  { id: 'cat-function-chairs', name: 'Function Chairs', slug: 'function-chairs', description: 'Plush velvet cushioned stackability banquet chairs for community halls.', image_url: '/carousel-1.jpg' },
  { id: 'cat-metal-chairs', name: 'Metal Chairs', slug: 'metal-chairs', description: 'Industrial steel stools, rust-resistant iron framing dining chairs.', image_url: '/images/designer-chairs.jpg' },
  { id: 'cat-arm-chairs', name: 'Arm Chairs', slug: 'arm-chairs', description: 'Classic teak wood armchairs, relaxing rocking chairs, and study arm chairs.', image_url: '/carousel-1.jpg' },
  { id: 'cat-tea-poys', name: 'Tea Poys', slug: 'tea-poys', description: 'Exquisite wooden center tables, sleek coffee stands, and nested utility tea poys.', image_url: '/carousel-1.jpg' },
  { id: 'cat-bureaus', name: 'Bureaus', slug: 'bureaus', description: 'Authentic heavy-gauge steel bureaus with security vaults for valuables.', image_url: '/images/steel-cupboards.jpg' },
  { id: 'cat-wardrobes', name: 'Wardrobes', slug: 'wardrobes', description: 'Multi-layer wood modular wardrobes, custom sliding doors with laminates.', image_url: '/carousel-1.jpg' },
  { id: 'cat-divans', name: 'Divans', slug: 'divans', description: 'Imperial wooden diwan cots carved by senior artisans of BVS Enterprises.', image_url: '/carousel-1.jpg' },
  { id: 'cat-book-shelves', name: 'Book Shelves', slug: 'book-shelves', description: 'Spacious vertical bookshelves, glass drawers showcase libraries.', image_url: '/images/bookshelves.jpg' },
  { id: 'cat-restaurant-furniture', name: 'Restaurant Furniture', slug: 'restaurant-furniture', description: 'Commercial diner counter tables, cafe tables, and banquet seats.', image_url: '/carousel-1.jpg' },
  { id: 'cat-school-furniture', name: 'School Furniture', slug: 'school-furniture', description: 'Dual student desks, classroom writing boards, and institutional school fixtures.', image_url: '/featured-3.jpg' },
  { id: 'cat-godown-furniture', name: 'Godown Furniture', slug: 'godown-furniture', description: 'Heavy slotted steel angle racking grids, industrial crates & pallets.', image_url: '/carousel-1.jpg' },
  { id: 'cat-swing-chairs', name: 'Swing Chairs', slug: 'swing-chairs', description: 'Premium wooden jhulas, modern balcony hanging swing chairs, and heavy brass-link ceiling swings.', image_url: '/images/swing-chairs.jpg' },
  { id: 'cat-bean-bags', name: 'Bean Bag Chairs', slug: 'bean-bag-chairs', description: 'Ultra-comfortable premium leatherette and dual-tone fabric bean bag chairs with triple-stitch safety.', image_url: '/images/bean-bags.jpg' }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-teak-cot',
    name: 'BVS Premium Apple-Motif King Cot',
    slug: 'bvs-premium-apple-motif-king-cot',
    description: 'Beautifully crafted designer solid teakwood king-size wooden bed showcasing elegant dual-tone contrast paneling and custom Apple-motif designer deep carvings on the headboard and footboard. Built with seasoned quality lumber to ensure termite immunity for life.',
    short_description: 'Solid teakwood king-size cot featuring the signature hand-carved Apple motif layout.',
    category_id: 'cat-beds',
    material: 'Seasoned Grade-A Burma Teakwood, Moisture Resistant Polyurethane Lacquer',
    dimensions: '75 x 72 x 42 inches (L x W x H)',
    brand: 'BVS Craftsmanship',
    price: 48500,
    sale_price: 43500,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '10 Years BVS Structural Warranty against wood borers or cracks.',
    emi_available: true,
    images: ['/carousel-1.jpg']
  },
  {
    id: 'prod-sofa-bed',
    name: 'BVS Royal Wooden Sofa-cum-Bed (Flower Cut)',
    slug: 'bvs-royal-wooden-sofa-cum-bed',
    description: 'Perfect space-saving master utility cot for family living rooms. Heavy rosewood frame showcasing gorgeous flower cuts on both arms. Easily slides out on metal rails to convert into a comfortable double mattress bed in seconds.',
    short_description: 'Solid mahogany multi-functional sofa-cum-bed with signature flower pattern cutout sides.',
    category_id: 'cat-sofas',
    material: 'Seasoned Hardwood Solid Frame, Premium High-Density Foam Cushions',
    dimensions: 'Sofa: 76 x 34 x 36 inches, Extended Bed: 76 x 60 x 18 inches',
    brand: 'BVS Premium',
    price: 36000,
    sale_price: 31500,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '5 Years Warranty on sliding rails and wooden structural integrity.',
    emi_available: true,
    images: ['/carousel-2.jpg']
  },
  {
    id: 'prod-home-set',
    name: 'BVS Classic Teak Sofa Set (3+1+1)',
    slug: 'bvs-classic-teak-sofa-set',
    description: 'Traditional wood-carved luxury sofa set. Features deep rich wood grains and classical curves, giving your living room ancestral prestige. Comprises one spacious 3-seater sofa and two comfortable matching single armchairs.',
    short_description: 'Classical 5-seater solid teakwood sofa set with premium melamine glaze.',
    category_id: 'cat-home-furniture',
    material: 'Burma Teak Wood, Semi-gloss finish, Premium Jacquard tapestry',
    dimensions: '3-Seater: 72 x 30 x 36 inches, Armchairs: 30 x 30 x 36 inches',
    brand: 'BVS Craftsmanship',
    price: 58000,
    sale_price: 52000,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '8 Years Warranty on timber warping.',
    emi_available: true,
    images: ['/images/sofa-sets.jpg']
  },
  {
    id: 'prod-exec-desk',
    name: 'BVS Executive Boss L-Shape Manager Desk',
    slug: 'bvs-executive-boss-l-shape-desk',
    description: 'Commanding office desk featuring pre-installed wire grommets, dual drawers with safety keys, and a return side table to house binders and desktop laptops.',
    short_description: 'Spacious high-end office manager table with sleek laminate protective coatings.',
    category_id: 'cat-office-furniture',
    material: 'Veneered Multilayer Plywood with Heat Resistant Borders',
    dimensions: '72 x 60 x 30 inches (Main Desk + Return Credenza)',
    brand: 'BVS Workspace',
    price: 34000,
    sale_price: 29500,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '3 Years Warranty on laminates and telescopic sliders.',
    emi_available: true,
    images: ['/images/office-furniture.jpg']
  },
  {
    id: 'prod-study-tab',
    name: 'BVS Modern Scholar Computer Study Table',
    slug: 'bvs-modern-scholar-study-table',
    description: 'Designed to maximize room workspace. Built with a dedicated CPU cabinet, keyboard slider, and top book storage shelving columns.',
    short_description: 'Smart wooden homework and computing study desk with top library column shelving.',
    category_id: 'cat-study-tables',
    material: 'Century Pre-Laminated Particle Wood & Heavy Hardware Keys',
    dimensions: '48 x 24 x 60 inches (L x W x H)',
    brand: 'BVS Scholar',
    price: 11000,
    sale_price: 8500,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '2 Years Structural Warranty.',
    emi_available: false,
    images: ['/images/office-furniture.jpg']
  },
  {
    id: 'prod-dining-tab',
    name: 'BVS Royal 6-Seater Teak dining set',
    slug: 'bvs-royal-6-seater-teak-dining-set',
    description: 'Elevate your dinings with a heavy solid teak wood table coupled with 6 padded high-back teak wooden chairs styled to perfection.',
    short_description: 'Luxurious heavy teakwood dining table set with 6 upholstered matching chairs.',
    category_id: 'cat-dining-tables',
    material: 'Solid Burma Teak, Royal Cushioning fabric',
    dimensions: '66 x 38 x 30 inches (L x W x H)',
    brand: 'BVS Premium',
    price: 54000,
    sale_price: 47900,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '10 Years BVS Carpentry Guarantee.',
    emi_available: true,
    images: ['/images/dining-tables.jpg']
  },
  {
    id: 'prod-ergo-chair',
    name: 'BVS Spine-Protect High-Back Mesh Chair',
    slug: 'bvs-spine-protect-high-back-mesh-chair',
    description: 'Ergonomically engineered for long computing hours. Equipped with neck and arm adjusting gears, tension locks, and gas cylinder leveling.',
    short_description: 'Premium spine support mesh office chair representing absolute ergonomic utility.',
    category_id: 'cat-office-chairs',
    material: 'Nylon Reinforced frame, Dynamic Lumbar Support, Class 4 Gas lift',
    dimensions: 'Adjustable height 46 to 52 inches',
    brand: 'BVS Active Support',
    price: 13500,
    sale_price: 9900,
    featured: true,
    customization_available: false,
    delivery_available: true,
    installation_available: true,
    warranty_details: '2 Years Replacement Warranty on pneumatic cylinder.',
    emi_available: false,
    images: ['/images/office-chairs.jpg']
  },
  {
    id: 'prod-plastic-ch',
    name: 'Nilkamal Heavy Duty Armless Chair (Set of 4)',
    slug: 'nilkamal-heavy-duty-armless-chair',
    description: 'Ultra robust molded high quality plastic chairs. Highly stackable, weatherproof, and designed to support up to 150kg weight easily.',
    short_description: 'Set of 4 genuine Nilkamal stackable plastic chairs for household functions.',
    category_id: 'cat-plastic-chairs',
    material: 'Virgin High-Density Polypropylene',
    dimensions: '22 x 20 x 32 inches',
    brand: 'Nilkamal',
    price: 3600,
    sale_price: 2900,
    featured: false,
    customization_available: false,
    delivery_available: true,
    installation_available: false,
    warranty_details: '1 Year Brand Manufacturer Warranty.',
    emi_available: false,
    images: ['/images/plastic-chairs.jpg']
  },
  {
    id: 'prod-banquet-ch',
    name: 'BVS Premium Velvet Red Marriage Hall Chair',
    slug: 'bvs-premium-velvet-red-banquet-chair',
    description: 'Elegant golden painted steel frame with thick lush red velvet padded seat and backrest. Perfect for wedding decorators and school halls.',
    short_description: 'Heavy duty stackable metal banquet function chair with royal gold finish.',
    category_id: 'cat-function-chairs',
    material: 'Carbon Steel Square pipes, Red Velvet Upholstery, Foam cushion',
    dimensions: '18 x 18 x 36 inches',
    brand: 'BVS Events',
    price: 1800,
    sale_price: 1450,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '3 Years frame welding warranty.',
    emi_available: false,
    images: ['/images/designer-chairs.jpg']
  },
  {
    id: 'prod-metal-ch',
    name: 'BVS Iron Bistro Accent Tolix Chair',
    slug: 'bvs-iron-bistro-accent-tolix-chair',
    description: 'Sleek metal construction representing modern minimalist cafe designs. Powder coated to avoid any rust, ideal for outdoor or indoor placement.',
    short_description: 'Rust-proof classic tolix metallic dining and outdoor cafe chair.',
    category_id: 'cat-metal-chairs',
    material: 'High-Strength Mild Steel sheets, Powder Coating finish',
    dimensions: '18 x 18 x 34 inches',
    brand: 'BVS Industrial',
    price: 2500,
    sale_price: 1950,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '2 Years Anti-rusting guarantee.',
    emi_available: false,
    images: ['/images/designer-chairs.jpg']
  },
  {
    id: 'prod-arm-ch',
    name: 'BVS Heritage Rosewood Relaxing Armchair',
    slug: 'bvs-heritage-rosewood-relaxing-armchair',
    description: 'Beautifully curved traditional armchair that offers excellent ergonomic comfort. Solid seasoned rosewood polished to highlight timber grains.',
    short_description: 'Classic handcrafted wooden armchair with premium rattan mesh weaving.',
    category_id: 'cat-arm-chairs',
    material: 'Seasoned Rosewood, Premium Quality Rattan caning',
    dimensions: '32 x 26 x 38 inches',
    brand: 'BVS Heritage',
    price: 12500,
    sale_price: 9800,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '5 Years Warranty against joints loosened.',
    emi_available: false,
    images: ['/images/designer-chairs.jpg']
  },
  {
    id: 'prod-teapoy',
    name: 'BVS Teakwood Royal Center Glass Tea-Poy',
    slug: 'bvs-teakwood-royal-center-glass-teapoy',
    description: 'Fabulous coffee/tea centerpiece showcasing beautiful carved wooden pillars beneath. Sits a thick 10mm bevelling tempered glass top representing high luxury tiers.',
    short_description: 'Elegant solid teakwood center tea-poy with tempered glass tabletop.',
    category_id: 'cat-tea-poys',
    material: 'Teakwood legs, 10mm Beveled heat-treated Glass',
    dimensions: '36 x 36 x 18 inches (L x W x H)',
    brand: 'BVS Craftsmanship',
    price: 9500,
    sale_price: 7800,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '5 Years Framework Warranty.',
    emi_available: false,
    images: ['/images/custom-furniture.jpg']
  },
  {
    id: 'prod-bureau',
    name: 'BVS Heavy Steel Almirah Bureau Secure Vault',
    slug: 'bvs-heavy-steel-almirah-bureau',
    description: 'Absolute protection for your valuable ornaments and silks. Built with 20-gauge heavy steel plating, secret locking lockers, and an embedded dressing mirror on front door panel.',
    short_description: 'Secure double-door heavy steel bureau with safety Locker and high dressing mirror.',
    category_id: 'cat-bureaus',
    material: 'Cold Rolled Steel sheets, Epoxy Powder Coating',
    dimensions: '78 x 36 x 20 inches (H x W x D)',
    brand: 'BVS Armour',
    price: 18500,
    sale_price: 15500,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '10 Years Warranty against rusting and lock mechanics.',
    emi_available: true,
    images: ['/images/steel-cupboards.jpg']
  },
  {
    id: 'prod-wardrobe',
    name: 'BVS Elite 3-Door Plywood Bedroom Wardrobe',
    slug: 'bvs-elite-3-door-plywood-wardrobe',
    description: 'Constructed from BWR boiling marine-grade plywood. Designed with sliding panels, golden handles, built-in hangers, and adjustable storage partitions.',
    short_description: 'Modular 3-door master plywood wardrobe with scratch-resistant premium laminates.',
    category_id: 'cat-wardrobes',
    material: 'Boiling Water Resistant Marine Plywood, Premium laminate finish',
    dimensions: '84 x 60 x 22 inches (H x W x D)',
    brand: 'BVS Customcraft',
    price: 49000,
    sale_price: 42000,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '10 Years BVS Cabinetry Warranty against timber pests.',
    emi_available: true,
    images: ['/images/wardrobes.jpg']
  },
  {
    id: 'prod-divan',
    name: 'BVS Royal Diwan Cot (Craftsman Carved)',
    slug: 'bvs-royal-diwan-cot-craftsman',
    description: 'Ancestral royalty styled diwan bedframe. Perfect for study rooms or lounge spaces. Solid seasoned wood columns with a gorgeous glossy wood sheen finish.',
    short_description: 'Classic carved wooden single diwan cot polished in high walnut melamine.',
    category_id: 'cat-divans',
    material: 'Seasoned Mahogany/Teak, melamine lacquer shine',
    dimensions: '72 x 30 x 16 inches',
    brand: 'BVS Heritage',
    price: 19000,
    sale_price: 15900,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '5 Years structural guarantee.',
    emi_available: false,
    images: ['/carousel-2.jpg']
  },
  {
    id: 'prod-booksh',
    name: 'BVS Glass-Door Scholar Bookshelf Cabinet',
    slug: 'bvs-glass-door-scholar-bookshelf',
    description: 'Keep your academic collection dust free. Features 5 deep shelves with elegant twin glass sliding panels and a key locking system.',
    short_description: 'Sturdy 5-shelf office and residential bookshelf with sliding glass protection.',
    category_id: 'cat-book-shelves',
    material: 'Century Pre-Laminated Wood Board, 5mm Toughened Glass panels',
    dimensions: '72 x 36 x 15 inches',
    brand: 'BVS Scholar',
    price: 14000,
    sale_price: 11500,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '3 Years Warranty on slide rollers and hinges.',
    emi_available: false,
    images: ['/images/bookshelves.jpg']
  },
  {
    id: 'prod-restaurant-set',
    name: 'BVS Classic 4-Seater Cafe Bistro Booth Set',
    slug: 'bvs-classic-4-seater-cafe-bistro-booth-set',
    description: 'Compact commercial restaurant dining. Includes one heavy laminated restaurant table and 4 metal cushioned high-back chairs perfectly sized for busy cafes.',
    short_description: '4-seater space-efficient commercial restaurant cafe table and chair pairing.',
    category_id: 'cat-restaurant-furniture',
    material: 'Iron stands, High-Pressure laminate board, Vinyl cushioned chairs',
    dimensions: 'Table: 48 x 30 x 30 inches, Chairs standard comfort',
    brand: 'BVS Commercial',
    price: 18000,
    sale_price: 14900,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '2 Years Commercial welding and joints warranty.',
    emi_available: false,
    images: ['/images/dining-tables.jpg']
  },
  {
    id: 'prod-student-bench',
    name: 'BVS Dual Student Classroom Desk Bench',
    slug: 'bvs-dual-student-classroom-desk-bench',
    description: 'Rugged iron chassis with wood boards supporting two students comfortably. Features safety hooks for school bags and a matching book holder row.',
    short_description: 'Heavy dual-student school bench desk with steel support framing.',
    category_id: 'cat-school-furniture',
    material: 'Seasoned Hardwood boarding, Powder coated heavy iron tubes',
    dimensions: '44 x 28 x 30 inches',
    brand: 'BVS Scholar',
    price: 6500,
    sale_price: 4900,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '5 Years industrial welding warranty.',
    emi_available: false,
    images: ['/images/office-furniture.jpg']
  },
  {
    id: 'prod-warehouse-rack',
    name: 'BVS Heavy Slotted Angle Storage Rack (5 Tiers)',
    slug: 'bvs-heavy-slotted-angle-storage-rack',
    description: 'Engineered for loading up to 200kg per tier slab. Steel angle borders are pre-punched for straightforward customization and alignment.',
    short_description: 'Industrial heavy duty 5-tier slotted steel warehouse angle racking unit.',
    category_id: 'cat-godown-furniture',
    material: 'Cold Rolled Steel, Industrial grey paint formulation',
    dimensions: '84 x 36 x 18 inches (H x W x D)',
    brand: 'BVS Armour',
    price: 11000,
    sale_price: 8500,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '3 Years Warranty against buckling or sag under rated load.',
    emi_available: false,
    images: ['/images/storage-racks.jpg']
  },
  {
    id: 'prod-swing-traditional',
    name: 'BVS Royal Teakwood Balcony Swing Jhula',
    slug: 'bvs-royal-teakwood-balcony-swing-jhula',
    description: 'Experience majestic tranquility with this royal balcony swing chair, custom hand-carved from seasoned Grade-A teakwood. Styled with an exquisite high-comfort fabric seat cushion and connected via rust-proof heavy solid brass hanging chains. Built to support up to 250kg weight easily.',
    short_description: 'Premium hand-carved solid teakwood balcony jhula with luxury brass hanging chains.',
    category_id: 'cat-swing-chairs',
    material: 'First-Grade Seasoned Burma Teak, Melamine Lacquer Finish, Solid Brass chains',
    dimensions: '50 x 24 x 28 inches (Seat Dimension)',
    brand: 'BVS Heritage',
    price: 32000,
    sale_price: 27500,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: true,
    warranty_details: '10 Years BVS Carpentry Guarantee on wood and frame joints.',
    emi_available: true,
    images: ['/images/swing-chairs.jpg']
  },
  {
    id: 'prod-swing-modern',
    name: 'BVS Cozy Nest Hanging Egg Chair',
    slug: 'bvs-cozy-nest-hanging-egg-chair',
    description: 'Modern tear-drop egg swing chair woven with durable high-density PE rattan on a heavy-duty reinforced steel stand. Includes ultra-plush, water-resistant tufted cushions for ultimate indoor or outdoor comfort.',
    short_description: 'Ergonomic PE rattan hanging egg-shaped swing chair with heavy metal base stand.',
    category_id: 'cat-swing-chairs',
    material: 'Reinforced Powder-Coated Carbon Steel, UV-Resistant PE Rattan, Water-Resistant Polyester Cushions',
    dimensions: 'Frame: 41 x 41 x 78 inches, Basket: 35 x 26 x 45 inches',
    brand: 'BVS Active Living',
    price: 18000,
    sale_price: 14900,
    featured: false,
    customization_available: false,
    delivery_available: true,
    installation_available: true,
    warranty_details: '2 Years Structural Warranty on metal frame and stand.',
    emi_available: false,
    images: ['/images/swing-chairs.jpg']
  },
  {
    id: 'prod-bean-classic',
    name: 'BVS Cloud Comfort Premium Leatherette Bean Bag (XXX-Large)',
    slug: 'bvs-cloud-comfort-leatherette-bean-bag',
    description: 'Sink into luxurious relaxation with our XXXL tear-drop shaped bean bag chair. Stitched with dual-protection zippers and double sewing from thick, scratch-proof premium leatherette. Pre-filled with premium high-density EPS beans that conform dynamically to your body posture.',
    short_description: 'Premium XXXL water-resistant leatherette bean bag pre-filled with high-density foam beans.',
    category_id: 'cat-bean-bags',
    material: 'Premium Heavy-Duty Matte Finish Leatherette, High-Density EPS Beans',
    dimensions: '46 x 46 x 40 inches (L x W x H)',
    brand: 'BVS Lounge',
    price: 4500,
    sale_price: 3490,
    featured: true,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '1 Year Warranty against zipper failures and stitching rips.',
    emi_available: false,
    images: ['/images/bean-bags.jpg']
  },
  {
    id: 'prod-bean-velvet',
    name: 'BVS Royal Plush Velvet Lounge Bean Bag',
    slug: 'bvs-royal-plush-velvet-lounge-bean-bag',
    description: 'Ultra-soft plush velvet bean bag chair designed for high-end lounge areas and bedrooms. Features a machine-washable removable velvet outer cover and a robust internal lining bag with secure child-safety zippers.',
    short_description: 'Elegant plush velvet bean bag with removable washable cover and secure internal liner.',
    category_id: 'cat-bean-bags',
    material: 'Premium High-Pile Washable Velvet, Internal Polyester Mesh Liner, Micro-EPS Beans',
    dimensions: '40 x 40 x 36 inches (L x W x H)',
    brand: 'BVS Lounge',
    price: 6000,
    sale_price: 4990,
    featured: false,
    customization_available: true,
    delivery_available: true,
    installation_available: false,
    warranty_details: '2 Years Warranty on fabric stitching and zippers.',
    emi_available: false,
    images: ['/images/bean-bags.jpg']
  }
];

export const INITIAL_VARIANTS: ProductVariant[] = [
  { id: 'v1', product_id: 'prod-teak-cot', variant_name: 'Premium Burmese Teak Wood (100% Solid)', variant_type: 'Material', additional_price: 0 },
  { id: 'v2', product_id: 'prod-teak-cot', variant_name: 'Premium Seasoned Rosewood (Sheesham)', variant_type: 'Material', additional_price: -4500 },
  { id: 'v3', product_id: 'prod-teak-cot', variant_name: 'King Size 78 x 72 inches', variant_type: 'Size', additional_price: 0 },
  { id: 'v4', product_id: 'prod-teak-cot', variant_name: 'Queen Size 78 x 60 inches', variant_type: 'Size', additional_price: -6000 },
  
  { id: 'v5', product_id: 'prod-sofa-bed', variant_name: 'Scratch-Resistant Performance Micro-Suede', variant_type: 'Upholstery', additional_price: 0 },
  { id: 'v6', product_id: 'prod-sofa-bed', variant_name: 'Premium Italian Napa Half Leatherette', variant_type: 'Upholstery', additional_price: 12000 },
  
  { id: 'v11', product_id: 'prod-wardrobe', variant_name: 'Glossy Anti-Scratch Century Laminates', variant_type: 'Door Finish', additional_price: 0 },
  { id: 'v12', product_id: 'prod-wardrobe', variant_name: 'Suede Matte Classic Laminates', variant_type: 'Door Finish', additional_price: -1200 }
];

export const INITIAL_INQUIRIES: ProductInquiry[] = [
  {
    id: 'inq-1',
    customer_name: 'Murali Mohan Naidu',
    mobile_number: '9845123049',
    product_id: 'prod-teak-cot',
    message: 'Hello BVS Enterprises, I am from Chandragiri road in Tirupati. I want to inspect this Teak Wood Cot this weekend.',
    inquiry_status: 'New',
    created_at: '2026-06-08T09:12:00Z'
  }
];

export const INITIAL_CUSTOM_REQUESTS: CustomFurnitureRequest[] = [
  {
    id: 'cust-1',
    customer_name: 'Kshitij Ramachandran',
    mobile_number: '9440552399',
    product_type: 'Study Table with Overhead Bookcase',
    custom_size: '6 feet width, 2.5 feet depth, 7 feet height',
    custom_material: 'Burma Teak Wood columns with laminated marine plywood shelves',
    custom_color: 'Rich Walnut finish paired with off-white cabinets',
    custom_design: 'Classic vintage table top with modern overhead floating shelves wrapped in safety LED strip profile groves.',
    finish_requirements: 'Smooth Melamine Semi-glass lacquer spray',
    special_requirements: 'Need 3 concealed brass lock-drawers for hard drives and document binders. Must deliver on next Friday.',
    reference_image_url: '/images/custom-furniture.jpg',
    message: 'Met your sales manager Mr. Prasad at the Tirupati Tilak road flagship store. Submitting my dimensions list here for reference.',
    status: 'In Progress',
    created_at: '2026-06-07T16:21:00Z'
  }
];

export const INITIAL_GALLERY: GalleryItem[] = [
  { id: 'gal-1', title: 'BVS Apple-Motif Premium King Bed', category: 'Home Furniture', image_url: '/carousel-1.jpg', featured: true, created_at: '2026-06-10T00:00:00Z' },
  { id: 'gal-2', title: 'BVS Royal Laser-Cut Sofa Cum Bed', category: 'Home Furniture', image_url: '/carousel-2.jpg', featured: true, created_at: '2026-06-12T00:00:00Z' },
  { id: 'gal-3', title: 'BVS Turned-Post English Teak Single Cot', category: 'Home Furniture', image_url: '/carousel-3.jpg', featured: true, created_at: '2026-06-15T00:00:00Z' },
  { id: 'gal-4', title: 'BVS Custom Dual Bunk Trundle Bed', category: 'Home Furniture', image_url: '/carousel-4.jpg', featured: true, created_at: '2026-06-18T00:00:00Z' },
  { id: 'gal-5', title: 'BVS Luxurious Wave-Cutout Sofa Cum Bed', category: 'Home Furniture', image_url: '/carousel-5.jpg', featured: true, created_at: '2026-06-20T00:00:00Z' },
  { id: 'gal-6', title: 'SV University Wooden Library Work Installations', category: 'Customer Installations', image_url: '/images/office-furniture.jpg', featured: true, created_at: '2026-06-21T00:00:00Z' },
  { id: 'gal-7', title: 'BVS Enterprise Corporate Partitioning Layout', category: 'Office Furniture', image_url: '/images/office-furniture.jpg', featured: true, created_at: '2026-06-21T02:00:00Z' }
];
